### ISSUE TITLE
Some question

### ISSUE THREAD

**Issue by Apiphoom** [KabirJaipal/A-Advance-Discord-Music-Bot-Like-Hydra-#2]
Can I request some music from channel that I setup and make discord bot join the voice channel that I'm in (not music voice channel from setup)

**Comment by GrouwBer** [comment]
how did you do it

**Comment by WoofWolfGG** [comment]
@Apiphoom Did you manage to do it?

**Comment by Apiphoom** [comment]
@WoofWolfGG yep
